
project_id = "xpxupanivlugsleqnvbr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
security_manual_linking_enabled = false

[db]
port = 54322

[edge_functions]
enabled = true
port = 54323

[functions.generate-ai-test]
verify_jwt = true

[functions.ai-study-chat]
verify_jwt = true

[studio]
enabled = true
port = 54323
